### PR TITLE
Image Scaling

### PR DESCRIPTION
**Pull request by tayvinw**
- Added logic to image_replacer to select a replacement image with an aspect ratio that is most relative to the original image. 
- Added functions to scale selected images without distortion and crop overflow. 
- Added logic to adjust margins for centering images but commented out because it looked better without it.

### CODE REVIEW

**Review by wy4tt — APPROVED** [review]
Looks to be sound logic

**Comment by rileyparish** [comment]
What's the plan to make this work when we have more than 4 images? This structure seems to imply that we'd need 4 separate lists of images (one for each aspect ratio) and we'd pull a random image from one of the lists depending on the aspect ratio. Is that what you had in mind? Have you found that images still get slightly skewed when they're replaced? Will the default case work with images that have an aspect ratio of 3:1 or 4:1?

I think it may be possible to use javascript to just add a CSS class to the  tag that will do all of the cropping/scaling for us. We'd write some CSS to resize any image to any size/aspect ratio and then just add that class to the img tag when we do a replace. I haven't looked into that approach much personally, but I feel like it could be more flexible/generally applicable.

**Comment by nathannelson97** [comment]
I also reviewed this and it looks good to me.

**Comment by jschaf14** [comment]
I also reviewed this lmao, looks good to me as well. GOOD JOB TAYVIN!

**Pull request merged**
